# Create a new comment
POST http://localhost:3000/api/comments HTTP/1.1
Content-Type: application/json

{
  "message": "wedw333wefwefccwcwewewf",
  "userId": "682b65ff16b8e0b9712a916e",
  "postId": "36a3d032-2b7e-4b13-85cd-c2386031b01d"
}