# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user1@notfosdfdund.local",
  "name": "Keks Smith 4",
  "password": "123456"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/683554ab9a8e7c3dff576cba HTTP/1.1

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user1@notfosdfdund.local",
  "password": "123456"
}

###