# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "test2@mail.local",
  "name": "Keks Smith 4",
  "password": "123456"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/683554ab9a8e7c3dff576cba HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODM2MGNlMDNkYjY0NmM2ZmE4OWU4ZDUiLCJlbWFpbCI6InVzZXIxQG5vdGZvc2RmZHVuZC5sb2NhbCIsIm5hbWUiOiJLZWtzIFNtaXRoIDQiLCJpYXQiOjE3NDkwMTg1MTksImV4cCI6MTc0OTAxODgxOX0.NdoqTAzWK81rSr9HXxfXlfUb8si8_GTwlae0xkp-GfA

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "test@mail.local",
  "password": "123456"
}

###